const INIT_SOCKET = 'INIT_SOCKET';
const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
const GET_ALL_FRIENDS = 'GET_ALL_FRIENDS';
const GET_ALL_TASKS = 'GET_ALL_TASKS';
const SEARCH_GROUP = 'SEARCH_GROUP';
const UPDATE_LISTENER = 'UPDATE_LISTENER';
const UPDATE_SENDERS = 'UPDATE_SENDERS';
const GET_GROUP_MEMBER = 'GET_GROUP_MEMBER';
const UPDATE_LISTENER_TARGET = 'UPDATE_LISTENER_TARGET';
const UPDATE_CONFIG_USAGE = 'UPDATE_CONFIG_USAGE';
const UPDATE_SEND_USAGE = 'UPDATE_SEND_USAGE';
const UPDATE_ADD_TASK_STATUS = 'UPDATE_ADD_TASK_STATUS';
const HAVE_UPDATE_GP_RELATIONSHIP = 'HAVE_UPDATE_GP_RELATIONSHIP';
const UPDATE_FRIENDS = 'UPDATE_FRIENDS';
const UPDATE_GROUPS = 'UPDATE_GROUPS';
const UPDATE_TARGET_GROUPS = 'UPDATE_TARGET_GROUPS';

export default {
  INIT_SOCKET,
  LOGIN_SUCCEED,
  GET_ALL_GROUPS,
  GET_ALL_FRIENDS,
  SEARCH_GROUP,
  UPDATE_LISTENER,
  UPDATE_SENDERS,
  GET_GROUP_MEMBER,
  GET_ALL_TASKS,
  UPDATE_LISTENER_TARGET,
  UPDATE_CONFIG_USAGE,
  UPDATE_SEND_USAGE,
  HAVE_UPDATE_GP_RELATIONSHIP,
  UPDATE_ADD_TASK_STATUS,
  UPDATE_FRIENDS,
  UPDATE_GROUPS,
  UPDATE_TARGET_GROUPS
};